apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: v1
    author: practice-f-sadatov
  name: nginx-named-port
  namespace: practice-f-sadatov
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: nginx-named-port
status:
  loadBalancer: {}
