apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-docker
  name: go-docker
  namespace: practice-f-sadatov
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-docker
status:
  loadBalancer: {}
